language: go
go:
 - '1.10'
branches:
  only:
  - main 
# Clean and don't fail
install:
  - rm -rf public || exit 0

# Build the website
script:
  - bin/hugo 

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: main 

after_script:
  - cd ./public
  - echo k.js.org > CNAME
  - git init
  - git config user.name "Kaiya"
  - git config user.email "xiongkaiya@gmail.com"
  - git add .
  - git commit -m "Update Blog By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  # Github Pages
  - git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" main:gh-pages 
  # Github Pages
  - git push --quiet "https://${GITHUB_TOKEN}@${GH_REF}" main:gh-pages --tags

env:
 global:
   # Github Pages
   - GH_REF: github.com/Kaiya/k.git
